name: Download  rips and Python examples from main ResInsight repository

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'  # Daily at 6 AM

jobs:
  download-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Set up authentication
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          echo "Authenticated with PAT"

      - name: Get latest successful workflow run
        id: get_run
        run: |
          curl -H "Authorization: token ${{ secrets.PAT }}" \
          https://api.github.com/repos/OPM/ResInsight/actions/workflows/ResInsightWithCache/runs \
          | jq '.workflow_runs[] | select(.conclusion=="success") | .id' \
          | head -n 1 > run_id.txt
          echo "run_id=$(cat run_id.txt)" >> $GITHUB_ENV

      - name: Download artifact
        run: |
          curl -H "Authorization: token ${{ secrets.PAT }}" \
          -L https://api.github.com/repos/OPM/ResInsight/actions/runs/${{ env.run_id }}/artifacts \
          -o artifact.zip


      - name: List downloaded files
        run: |
          echo "Downloaded files:"
          ls -la .
