name: Download  rips and Python examples from main ResInsight repository

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'  # Daily at 6 AM

jobs:
  download-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up authentication
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          echo "Authenticated with PAT"

      - name: Get latest successful workflow run
        id: get_run
        run: |
          curl -H "Authorization: token ${{ secrets.PAT }}" \
          https://api.github.com/repos/OPM/ResInsight/actions/workflows/ResInsightWithCache.yml/runs \
          | jq '.workflow_runs[] | select(.conclusion=="success") | .id' \
          | head -n 1 > run_id.txt
          echo "run_id=$(cat run_id.txt)" >> $GITHUB_ENV

      - name: Download artifact metadata
        id: get_artifact
        run: |
          mkdir -p downloaded_artifacts
          curl -H "Authorization: token ${{ secrets.PAT }}" \
          -L https://api.github.com/repos/OPM/ResInsight/actions/runs/${{ env.run_id }}/artifacts \
          -o downloaded_artifacts/artifacts.json
          # Find artifact with name python-distribution
          ARTIFACT_URL=$(jq -r '.artifacts[] | select(.name=="python-distribution") | .archive_download_url' downloaded_artifacts/artifacts.json)
          echo "artifact_url=$ARTIFACT_URL" >> $GITHUB_ENV

      - name: Download artifact file
        run: |
          curl -H "Authorization: token ${{ secrets.PAT }}" \
          -L "${{ env.artifact_url }}" \
          -o downloaded_artifacts/artifact.zip

      - name: List downloaded files
        run: |
          echo "Downloaded files:"
          mkdir upstream_rips

          cd downloaded_artifacts
          unzip artifact.zip
          cd ..
          tar -xzf downloaded_artifacts/rips*.tar.gz -C upstream_rips
          ls upstream_rips/rips*
          cp -r upstream_rips/rips*/rips ./docs/
          ls -R ./docs/rips

      - name: Create Read the Docs Python examples
        run: |
          python docs/source/create_python_examples.py

      - name: Upload to current repository
        uses: actions/upload-artifact@v4
        with:
          name: rips-and-examples
          path: downloaded_artifacts/

      - uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update rips module and Python examples"
          title: "Automated fixes of rips from ResInsight artifacts"
          branch: artifact-update-rips
          branch-suffix: random   
